Repository filipemelo2002/gama-bank, pull requests merged in 2021-02, with the labels that each got.

#18 Fixed Menu style and behaviour
  src/components/Menu/index.tsx
  src/components/Menu/style.ts
  src/img/pix.svg
  src/pages/dashBoard/index.tsx
Labels: bug, enhancement, feature

#19 added routing links to menu options
  src/components/Menu/index.tsx
  src/pages/dashBoard/index.tsx
  src/pages/dashBoard/style.ts
Labels: enhancement, feature

#20 Finished new Project Interface
  src/pages/dashBoard/Deposits/index.tsx
  src/pages/dashBoard/Deposits/style.ts
  src/pages/dashBoard/Home/index.tsx
  src/pages/dashBoard/Home/style.ts
  src/pages/dashBoard/Payments/index.tsx
  src/pages/dashBoard/Payments/style.ts
  src/pages/dashBoard/index.tsx
  src/pages/dashBoard/style.ts
  src/style/global.ts
Labels: enhancement, feature

#22 Feature/dashboard plans resource
  src/components/ItemExpense/index.tsx
  src/components/ItemIncome/index.tsx
  src/pages/dashBoard/Planning/index.tsx
  src/pages/dashBoard/Planning/style.ts
Labels: enhancement, feature

#21 Add api integration on dashboard Home
  src/pages/dashBoard/Home/index.tsx
  src/pages/dashBoard/Home/style.ts
  src/utils/getDate.ts
  src/utils/toMoney.ts
Labels: feature

#24 Finished Planning Screen
  src/@types/planning.d.ts
  src/@types/state.d.ts
  src/api/planning.ts
  src/redux/action/planning.ts
  src/redux/reducer/index.ts
  src/redux/reducer/planning.ts
Labels: enhancement, feature
